apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cots-platform

helmGlobals:
  chartHome: charts

helmCharts:
  - name: cots-frontend
    releaseName: cots
    namespace: cots-platform
    valuesFile: values.yaml

patches:
  - target:
      kind: Deployment
      name: cots-frontend
    patch: |
      - op: replace
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
