apiVersion: apps/v1
kind: Deployment
metadata:
  name: cots-api
  namespace: cots-platform
spec:
  selector:
    matchLabels:
      app: cots-api
  template:
    metadata:
      labels:
        app: cots-api
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
