apiVersion: apps/v1
kind: Deployment
metadata:
  name: cots-worker
  namespace: cots-platform
spec:
  selector:
    matchLabels:
      app: cots-worker
  template:
    metadata:
      labels:
        app: cots-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: null
        runAsGroup: null
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              add: []
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
